### ISSUE TITLE
Facing a issue when I change the Shader to blinn or others shaders

### ISSUE THREAD

**Issue by YozoraNT** [JakobJK/modelChecker#12]
the Shaders checkers showing Fails result when I change the shader from lambert to any others shaders.
how should I do to solve this issue ?

**Comment by JakobJK** [comment]
So in many studios environments the models should be published with the default shader on. So all this check is doing, is checking if other shaders than default lambert1 is involved. If that is not valid for your needs, simply don't check for that.
