### ISSUE TITLE
Latest version doesn't work with maya 2018

### ISSUE THREAD

**Issue by astandarduser** [JakobJK/modelChecker#14]
I get the error

`modelChecker_UI.UI.show_UI()
# Error: SyntaxError: file <maya console> line 1: invalid syntax # 
from modelChecker import modelChecker_UI

modelChecker_UI.UI.show_UI()
# Error: SyntaxError: file <maya console> line 1: invalid syntax # `

**Comment by JakobJK** [comment]
Yes. Support for Python 2 is gone. ;(

The older version should still provide you with similar checks though.

**Comment by JakobJK** [comment]
@astandarduser, my arm is being twisted.

I'll make it Python 2 compatible again in the next update, which should make it work in 2018 again. Sorry for the inconvenience.

**Comment by JakobJK** [comment]
@astandarduser The latest update has been merged. Feel free to give it a shot, and please file another issue if you run into anything. It hasn't been fully tested on windows, so I am sure there will be a few things I'll have to iron out. Thank you!
