### ISSUE TITLE
freeze / high cpu usage when object is not selected 

### ISSUE THREAD

**Issue by adevra** [JakobJK/modelChecker#18]
freeze / extreme cpu usage when object is not selected in viewport and **run checks on selected/all** 
happens only on running the tool the second time.
also same behavior when hitting **clear**.

maya 2022 / 2024

**Comment by JakobJK** [comment]
Thanks for reporting. Does this happen on a fairly light scene as well? What OS are you on? If you have no objects selected (and aren't managing individual contexts, you are essentially running checks on everything inside of your current maya session which can be expensive)
