### ISSUE TITLE
M2024 compatibility issue?

### ISSUE THREAD

**Issue by safeburton** [JakobJK/modelChecker#19]
Has anyone else managed to get this running in M2024?

I have copied the py files to the folder then run the command 

```
from modelChecker import modelChecker_UI

modelChecker_UI.UI.show_UI()

```
All i get back is this error

`# Error: ModuleNotFoundError: file <maya console> line 1: No module named 'modelChecker'`

**Comment by JakobJK** [comment]
The modelChecker should work in 2024.

If Maya is not able to find the modelChecker module, it's most likely that the modelChecker is not located in a proper scripts folder. Make sure that the modelChecker folder is in a folder that is visible to python in Maya.

You can check in mayas script editor by running:
```python
import sys
for p in sys.path:
    print(p)
```
As an example, if this directory shows up: `C:\Users\jakob\Documents\maya\2024\prefs\scripts`

You can put the modelChecker folder in that directory so the files would look like this:
`C:\Users\jakob\Documents\maya\2024\prefs\scripts\modelChecker\__init__.py`
`C:\Users\jakob\Documents\maya\2024\prefs\scripts\modelChecker\__version__.py`
.... etc

Let me know if this helps. Thanks!
