### ISSUE TITLE
Issue with Maya 2025

### ISSUE THREAD

**Issue by RooVFX** [JakobJK/modelChecker#22]
Hello 

Hopefully looking for a solution, everything seems to be in place with folder location etc. but when i try to run it i get an error im unsure how to fix 

/Documents/maya/scripts\modelChecker\modelChecker_UI.py line 1: No module named 'PySide2'

Any ideas ?

**Comment by RooVFX** [comment]
Heyo just checking in to see if there had been any thoughts on this one ?

**Comment by JakobJK** [comment]
2025 uses PySide6, and not PySide2, so it should be an easy fix. I'll see if I can squeeze it in this week.

**Comment by RooVFX** [comment]
that would be amazing thank you so much

**Comment by JakobJK** [comment]
It should be solved now, but let me know if you are still experiencing issues.
