### ISSUE TITLE
2018 issues

### ISSUE THREAD

**Issue by astandarduser** [JakobJK/modelChecker#7]
The latest changes seem to break in maya 2018

modelChecker_UI.UI.show_UI()
# Error: SyntaxError: file C:/Users/USER/Documents/maya/2018/scripts\modelChecker\modelChecker_UI.py line 15: invalid syntax #

**Comment by JakobJK** [comment]
Thanks for filing the issue! I just merged a pr that will likely solve it! Let me know if it is still bugging out though.

**Comment by astandarduser** [comment]
Works perfect now :) thanks for creating such a useful tool

**Comment by JakobJK** [comment]
Awesome!! Thank you so much for using it.
